version: "3.7"
services:
  nginx:
    image: nginx:alpine
    volumes:
      - .:/var/www/html
      - ./nginx/jigsaw.conf:/etc/nginx/conf.d/default.conf
    environment:
      VIRTUAL_HOST: jigsaw.docker
    networks:
      - network

  phpfpm:
    image: joshrob/php73fpm
    volumes:
      - .:/var/www/html
      - ~/.composer:/root/.composer
    environment:
      XDEBUG_CONFIG: remote_host=192.168.0.18
    networks:
      - network

  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jigsaw
      MYSQL_USER: jigsaw
      MYSQL_PASSWORD: jigsaw

    volumes:
      - data_volume:/var/lib/mysql
    networks:
      - network

  adminer:
    image: adminer
    restart: always
    environment:
      VIRTUAL_HOST: adminer.docker
    networks:
      - network

  chrome:
    image: robcherry/docker-chromedriver
    networks:
      - network
    environment:
      CHROMEDRIVER_WHITELISTED_IPS: ""
      CHROMEDRIVER_PORT: "9515"
    ports:
      - 9515:9515
    cap_add:
      - "SYS_ADMIN"

volumes:
  data_volume:

networks:
  network: